// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package authdto

import (
	customer "github.com/ARTMUC/magic-video/internal/domain/customer"
	service "github.com/ARTMUC/magic-video/internal/service"
)

type DtoConverterImpl struct{}

func (c *DtoConverterImpl) CustomerToGetCustomerOutputBody(source *customer.Customer) *GetCustomerOutputBody {
	var pAuthdtoGetCustomerOutputBody *GetCustomerOutputBody
	if source != nil {
		var authdtoGetCustomerOutputBody GetCustomerOutputBody
		authdtoGetCustomerOutputBody.BaseModel = BaseToBase((*source).BaseModel)
		authdtoGetCustomerOutputBody.Email = (*source).Email
		authdtoGetCustomerOutputBody.Name = NullStringToStringPtr((*source).Name)
		authdtoGetCustomerOutputBody.AddressHomeNumber = NullStringToStringPtr((*source).AddressHomeNumber)
		authdtoGetCustomerOutputBody.AddressStreetName = NullStringToStringPtr((*source).AddressStreetName)
		authdtoGetCustomerOutputBody.AddressCity = NullStringToStringPtr((*source).AddressCity)
		authdtoGetCustomerOutputBody.AddressZipCode = NullStringToStringPtr((*source).AddressZipCode)
		authdtoGetCustomerOutputBody.AddressState = NullStringToStringPtr((*source).AddressState)
		authdtoGetCustomerOutputBody.AddressCountryCode = NullStringToStringPtr((*source).AddressCountryCode)
		pAuthdtoGetCustomerOutputBody = &authdtoGetCustomerOutputBody
	}
	return pAuthdtoGetCustomerOutputBody
}
func (c *DtoConverterImpl) SessionToCustomerAuthSigninOutputBody(source *service.SessionOutput) *CustomerAuthSigninOutputBody {
	var pAuthdtoCustomerAuthSigninOutputBody *CustomerAuthSigninOutputBody
	if source != nil {
		var authdtoCustomerAuthSigninOutputBody CustomerAuthSigninOutputBody
		authdtoCustomerAuthSigninOutputBody.Token = (*source).Token
		authdtoCustomerAuthSigninOutputBody.RefreshToken = (*source).RefreshToken
		pAuthdtoCustomerAuthSigninOutputBody = &authdtoCustomerAuthSigninOutputBody
	}
	return pAuthdtoCustomerAuthSigninOutputBody
}
